services:
  data-generator:
    build:
      context: ./data-generator-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - dataflow-network

  data-filter:
    build:
      context: ./data-filter-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      rabbitmq:
        condition: service_healthy
      data-generator:
        condition: service_started
    networks:
      - dataflow-network
    volumes:
      - dataflow:/data/dataflow

  data-mongodb-writer:
      build:
        context: ./data-mongodb-writer-service
        dockerfile: Dockerfile
      environment:
        SPRING_AMQP_DESERIALIZATION_TRUST_ALL: true
      ports:
        - "8084:8084"
      depends_on:
        - rabbitmq
        - mongodb
        - data-filter
      networks:
        - dataflow-network

  data-db-writer:
      build:
        context: ./data-db-writer-service
        dockerfile: Dockerfile
      ports:
        - "8085:8085"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dataflow
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
        SPRING_RABBITMQ_HOST: rabbitmq
        SPRING_RABBITMQ_PORT: 5672
        SPRING_RABBITMQ_USERNAME: guest
        SPRING_RABBITMQ_PASSWORD: guest
        SPRING_AMQP_DESERIALIZATION_TRUST_ALL: true
        SPRING_REDIS_HOST: redis
        SPRING_REDIS_PORT: 6379
      depends_on:
        - rabbitmq
        - postgres
        - data-filter
        - redis
      networks:
        - dataflow-network

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=dataflow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dataflow-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - dataflow-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    networks:
      - dataflow-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - dataflow-network
  
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - dataflow-network
    depends_on:
      - data-generator
      - data-filter
      - rabbitmq

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - dataflow-network
    depends_on:
      - prometheus

networks:
  dataflow-network:
    driver: bridge

volumes:
  postgres_data:
  mongodb_data:
  dataflow: