server:
  port: 8082

spring:
  application:
    name: data-filter-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      batch-size: 16384  # 16 KB
      buffer-memory: 33554432  # 32 MB buffer
      properties:
        compression.type: snappy
        linger.ms: 10
        request.timeout.ms: 30000
        max.block.ms: 30000
        acks: all
        retries: 3
        retry.backoff.ms: 1000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

# WebSocket Configuration
websocket:
  generator:
    url: ws://data-generator:8081/ws/data
    max-retries: 5
    retry-delay-ms: 2000

# Kafka Topics Configuration
kafka:
  topic:
    name: data-topic
    partitions: 3
    replication-factor: 1

# File Storage Configuration
storage:
  base-path: /data/dataflow
  paths:
    filtered: ${storage.base-path}/filtered
    archive: ${storage.base-path}/archive
    temp: ${storage.base-path}/temp
  retention:
    days: 30
  flush-interval-ms: 5000

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
    instances:
      webSocketCircuitBreaker:
        baseConfig: default
      kafkaCircuitBreaker:
        baseConfig: default
      fileWriterCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
      websocketHandlerCircuitBreaker:
        baseConfig: default
  retry:
    instances:
      websocketRetry:
        maxAttempts: 3
        waitDuration: 2000
        exponentialBackoffMultiplier: 2
      kafkaRetry:
        maxAttempts: 5
        waitDuration: 1000
        exponentialBackoffMultiplier: 1.5
      fileWriterRetry:
        maxAttempts: 4
        waitDuration: 1500

# Monitoring Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,circuitbreakers
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    kafka:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        resilience4j.circuitbreaker.calls: true
        kafka.producer: true

# Logging Configuration
logging:
  level:
    com.dataflow.dataflowsystem.filter: DEBUG
    org.apache.kafka: INFO