apiVersion: 1

datasources:
  - name: 'Prometheus'
    type: 'prometheus'
    access: 'proxy'
    url: 'http://prometheus:9090'
    isDefault: true

  - name: 'RabbitMQ'
    type: 'prometheus'
    access: 'proxy'
    url: 'http://rabbitmq:15692'