# Server Configuration
server:
  port: 8081

# Application Configuration
spring:
  application:
    name: data-generator-service

# WebSocket Configuration
websocket:
  max-retry-attempts: 3
  cleanup-interval-ms: 60000

# Monitoring Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true

# Logging Configuration 
logging:
  level:
    com.dataflow.dataflowsystem.generator: DEBUG