# Server Configuration
server:
  port: 8081

# Application Configuration
spring:
  application:
    name: data-generator-service

# WebSocket Configuration
websocket:
  max-retry-attempts: 3
  cleanup-interval-ms: 60000

# Monitoring Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true

# Logging Configuration 
logging:
  level:
    com.dataflow.dataflowsystem.generator: DEBUG

filter-service:
  health-check-url: http://data-filter:8082/actuator/health


resilience4j:
  circuitbreaker:
    instances:
      filterServiceCircuitBreaker:
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2000ms
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        automaticTransitionFromOpenToHalfOpenEnabled: true
